# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZNkA_BK8gqBc51zCxb-8f4jEMLVy9ORK
"""
a=float(input("Enter a : "))
b=float(input("Enter b : "))
op=input("Enter the operator : ")

def add(a,b):
  print("The Sum is",a+b)

def sub(a,b):
  print("The Difference of",a," and ",b,"is",a-b)

def mul(a,b):
  print("The Sum is",a*b)

def div(a,b):
  print("The Sum is",a/b)

if(op=='+'):
  add(a,b)
elif(op=='-'):
  sub(a,b)
elif(op=='*'):
  mul(a,b)
elif(op=='/'):
  div(a,b)
else:
  print("Invalid input")