# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZNkA_BK8gqBc51zCxb-8f4jEMLVy9ORK
"""

a=float(input("Enter a : "))
b=float(input("Enter b : "))
op=input("Enter the operator : ")

def add(a,b):
  print("The Sum is",a+b)

def sub(a,b):
  print("The Difference of",a," and ",b,"is",a-b)

def mul(a,b):
  print("The Sum is",a*b)

def div(a,b):
  print("The Sum is",a/b)

if(op=='+'):8
  add(a,b)
elif(op=='-'):
  sub(a,b)
elif(op=='*'):
  mul(a,b)
elif(op=='/'):
  div(a,b)
else:
  print("Invalid input")

import numpy as np

a=float(input("Enter a : "))
b=float(input("Enter b : "))
c=float(input("Enter c : "))

r1=(-b+np.sqrt(b**2 - 4*a*c))/(2*a)
r2=(-b-np.sqrt(b**2 - 4*a*c))/(2*a)

print("First root : ",r1)
print("Second root : ",r2)

import cmath as np

a=float(input("Enter a : "))
b=float(input("Enter b : "))
c=float(input("Enter c : "))

r1=(-b+np.sqrt(b**2 - 4*a*c))/(2*a)
r2=(-b-np.sqrt(b**2 - 4*a*c))/(2*a)

print("First root : ",r1)
print("Second root : ",r2)

def reverse_number(number):
    original_number = number
    reverse = 0

    for _ in str(number):
        digit = number % 10
        reverse = reverse * 10 + digit
        number //= 10

    print(f"Original Number: {original_number}")
    print(f"Reversed Number: {reverse}")

# Example Usage
reverse = 6789
reverse_number(reverse)

#Reverse of a number

n=int(input("Enter the value of n : "))
def rev_number(n):
  rev_num=0
  while(n!=0):
    d=n%10
    rev_num=rev_num*10+d
    n=n//10
  print(rev_num)
rev_number(n)

n=int(input("Enter n : "))
fact=1
for i in range (1,n+1):
  fact=fact*i
print(fact)

# Swap

a=10
b=20

a,b=b,a

print(a)
print(b)

# Program to display the calender

import calendar

year=int(input("Enter the Year : "))
month=int(input("Enter the Month : "))

cal=calendar.month(year,month)
print(cal)

help(calendar)